### ISSUE TITLE
I have compat I made!

### ISSUE THREAD

**Issue by OutrightWings** [PssbleTrngle/DyeTheWorld#1]
### Describe the feature you have in mind.

You can use these
[Dye_Depot_Compat_Textures.zip](https://github.com/user-attachments/files/17690503/Dye_Depot_Compat_Textures.zip)
[Dye_Depot_Compat_Data.zip](https://github.com/user-attachments/files/17690504/Dye_Depot_Compat_Data.zip)

**Comment by PssbleTrngle** [comment]
Oh very nice, will likely not include any of them initial release since I want to get that out now, but in a further update later this week.
How did you even find this project, it's still unlisted?

**Comment by OutrightWings** [comment]
Its not unlisted! On modrinth there is published files. Happened to just be curious if other made compat and ran into you.

**Comment by PssbleTrngle** [comment]
Ahh, the project itself is still unlisted (not visible in search), but it has already been added to the compat list, I was just confused how you found it 😅

**Comment by PssbleTrngle** [comment]
But I will release it publicly later tonight & depending on how much time I have I will maybe already integrate some of your textures, if you send me your modrinth/curseforge username I can also add you as an artist their then

**Comment by OutrightWings** [comment]
It's outrightwings. I appreciate your project!

**Comment by PssbleTrngle** [comment]
I've just released the first public release. I've included your valve handle textures as well as the awnings and buntings. The awnings will likely receive a retexture somewhen down the line to give the patterns like the other ones, but thank you very much for providing me with the textures. I will also very likely use the textures for the other mods you did in a future release down the line

**Comment by OutrightWings** [comment]
No worries! And yeah they are rough, but it beats having missing texture items :) glad they can be of use.

**Comment by PssbleTrngle** [comment]
Hi, I've just released a new version which should now include all of the textures you did. I only tweaked the shipping containers a bit by desaturating the textures, since the ones for the vanilla colors where way less saturated, I hope that's alright with you.
Thank you very much again for your help ❤️
