### ISSUE TITLE
Some problems with canvas signs

### ISSUE THREAD

**Issue by Zeykehasnt** [PssbleTrngle/DyeTheWorld#7]
### What happened?

First of all. They don't break fast with an axe since they don't have a proper tag.
Second. They have the lack of tags, yep.
Third. They can't be washed with soap from the supplementaries.
![image](https://github.com/user-attachments/assets/f774f2b2-2008-44d8-af7f-1462993ef265)
![image](https://github.com/user-attachments/assets/56ec42f0-961c-4113-9c38-66a184089846)
![image](https://github.com/user-attachments/assets/dbbc63ea-8263-4c5c-a467-72e266266b85)
![image](https://github.com/user-attachments/assets/a36d92e7-23ee-4ce8-a68b-2fb9cb82811b)

### Loader

forge

### Mod Version

1.0.1

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Should be fixed in `1.1.0`
