### ISSUE TITLE
Dye the world terracotta bricks and radon lamps are missing `mineable/pickaxe` tag

### ISSUE THREAD

**Issue by thelegitdolt** [PssbleTrngle/DyeTheWorld#8]
### What happened?

Using dye the world 1.0.1

### Loader

forge

### Mod Version

1.0.1

### Minecraft Version

1.20

**Comment by Giubbottoman** [comment]
The same tag is missing from terracotta shingles [quark] and their respective stairs, slabs, etc.

**Comment by PssbleTrngle** [comment]
Should be fixed in `1.1.0`
