### ISSUE TITLE
Breaks forge:glass tag.

### ISSUE THREAD

**Issue by Screamermod** [PssbleTrngle/DyeTheWorld#9]
### What happened?

Forge:glass and forge:glass_pane are empty tags.

### Loader

forge

### Mod Version

dye_the_world-1.0.1

### Minecraft Version

1.20

**Comment by Screamermod** [comment]
(The forge:meat part was an error on my part, actually, disregard that.)

**Comment by PssbleTrngle** [comment]
Should be fixed in `1.1.0`
